/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jrsync;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Administrator
 */
public class AddHostWork extends javax.swing.JFrame {
    
    private HostWork hostwork = new HostWork();
    String rsyncCmdString;
    //private ArrayList<HostWork> hostworks;
    private DefaultListModel<HostWork> dlmhw;
    
    /**
     * Creates new form AddHost
     */
    public AddHostWork(DefaultListModel<HostWork> dlmhw) {
        
        initComponents();       
        this.dlmhw = dlmhw;       
        rsyncCmdString = jTrsyncCmd.getText();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTuserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTremoteHost = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTremoteDir = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTlocalDir = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTBackupCmd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTrecoverCmd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTrsyncCmd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RemoteHost", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 15), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel5.setText("user:");

        jTuserName.setToolTipText("root");
        jTuserName.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTuserNameCaretUpdate(evt);
            }
        });

        jLabel1.setText("target host：");

        jTremoteHost.setToolTipText("192.168.0.250");
        jTremoteHost.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTremoteHostCaretUpdate(evt);
            }
        });
        jTremoteHost.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTremoteHostInputMethodTextChanged(evt);
            }
        });

        jLabel6.setText("remote directory：");

        jTremoteDir.setToolTipText("/home/   末尾斜杠不能少，表示备注home/下子目录，便于还原。");
        jTremoteDir.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTremoteDirCaretUpdate(evt);
            }
        });

        jLabel9.setForeground(java.awt.Color.blue);
        jLabel9.setText("远程目录和本地目录，需要以/结束，比如/home/ ，表示备份子目录，便于还原作业。");
        jLabel9.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTremoteDir, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTremoteHost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(jTuserName, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTuserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTremoteHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTremoteDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LocalHost", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 15), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel2.setText("local directory:");

        jTlocalDir.setToolTipText("/data1/250home/  末尾斜杠不可少，便于还原作业。");
        jTlocalDir.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTlocalDirCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTlocalDir, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTlocalDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RsyncCmd", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 0, 15), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel3.setText("rsync command:");

        jTBackupCmd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTBackupCmdFocusGained(evt);
            }
        });
        jTBackupCmd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBackupCmdMouseClicked(evt);
            }
        });

        jLabel4.setText("restore command:");

        jTrecoverCmd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTrecoverCmdFocusGained(evt);
            }
        });
        jTrecoverCmd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTrecoverCmdMouseClicked(evt);
            }
        });
        jTrecoverCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrecoverCmdActionPerformed(evt);
            }
        });

        jLabel7.setText("Rsync cmd：");

        jTrsyncCmd.setText("rsync -a --delete");
        jTrsyncCmd.setToolTipText("rsync -a --delete");
        jTrsyncCmd.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTrsyncCmdCaretUpdate(evt);
            }
        });
        jTrsyncCmd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTrsyncCmdFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTrsyncCmd, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTBackupCmd, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addComponent(jTrecoverCmd))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTrsyncCmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTBackupCmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTrecoverCmd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("AddHost");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("添加完毕之后，请在主窗口点击保存以保存修改。");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTremoteHostInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTremoteHostInputMethodTextChanged
      
        
    }//GEN-LAST:event_jTremoteHostInputMethodTextChanged

    private void jTremoteHostCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTremoteHostCaretUpdate
        String rhostnameString = jTremoteHost.getText();
        hostwork.getHost().setrhost(rhostnameString);
    }//GEN-LAST:event_jTremoteHostCaretUpdate

    private void jTlocalDirCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTlocalDirCaretUpdate
       String lhostDirString = jTlocalDir.getText();
       hostwork.getHost().setlhostDir(lhostDirString);
      
    }//GEN-LAST:event_jTlocalDirCaretUpdate

    private void jTuserNameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTuserNameCaretUpdate
       String rhostUserString = jTuserName.getText();
        hostwork.getHost().setrhostUser(rhostUserString);
    }//GEN-LAST:event_jTuserNameCaretUpdate

    private void jTremoteDirCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTremoteDirCaretUpdate
        String rhostdirString = jTremoteDir.getText();
        hostwork.getHost().setrhostDir(rhostdirString);
        
    }//GEN-LAST:event_jTremoteDirCaretUpdate

    private void jTrsyncCmdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTrsyncCmdCaretUpdate
       rsyncCmdString = jTrsyncCmd.getText();
        
    }//GEN-LAST:event_jTrsyncCmdCaretUpdate

    private void jTBackupCmdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBackupCmdMouseClicked
           updateHost();
       
    }//GEN-LAST:event_jTBackupCmdMouseClicked

    private void jTBackupCmdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTBackupCmdFocusGained
        updateHost();
        
    }//GEN-LAST:event_jTBackupCmdFocusGained

    private void jTrecoverCmdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTrecoverCmdFocusGained
        updateHost();
       
    }//GEN-LAST:event_jTrecoverCmdFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        updateHost();
        //MJFrame.addNewHost(hostnow);
        this.dlmhw.addElement(hostwork);        
        //this.dlmhw.add(hostwork);
        this.dispose();
        //MJFrame.update();        
       // hostnow = new Host();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTrecoverCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrecoverCmdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTrecoverCmdActionPerformed

    private void jTrecoverCmdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTrecoverCmdMouseClicked
        // TODO add your handling code here:
         updateHost();
        
    }//GEN-LAST:event_jTrecoverCmdMouseClicked

    private void jTrsyncCmdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTrsyncCmdFocusGained
        // TODO add your handling code here:
        rsyncCmdString = jTrsyncCmd.getText();
    }//GEN-LAST:event_jTrsyncCmdFocusGained

    
    public void updateHost(){
        
          //hostwork.getHost().setrhostUser(rhostUserString);
          //hostwork.getHost().setrhost(rhostnameString);
         // hostwork.getHost().setrhostDir(rhostdirString);
          //hostwork.getHost().setlhostDir(lhostDirString);
          hostwork.getHost().setrsyncCmd(rsyncCmdString);
          
          hostwork.getHost().upDateHost(); //.updatetheHost();
          
          jTBackupCmd.setText(hostwork.getHost().getbackupCmdString()); //w.getbackupCmd());
          jTrecoverCmd.setText(hostwork.getHost().getrecoverCmdString());
            //hostnow.getrecoverCmd());
          
       }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTBackupCmd;
    private javax.swing.JTextField jTlocalDir;
    private javax.swing.JTextField jTrecoverCmd;
    private javax.swing.JTextField jTremoteDir;
    private javax.swing.JTextField jTremoteHost;
    private javax.swing.JTextField jTrsyncCmd;
    private javax.swing.JTextField jTuserName;
    // End of variables declaration//GEN-END:variables
}
